/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'
import { Route as ExamsExamIdIndexRouteImport } from './routes/exams.$examId.index'
import { Route as ExamsExamIdPaperIdRouteImport } from './routes/exams.$examId.$paperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdIndexRoute = ExamsExamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamsExamIdRoute,
} as any)
const ExamsExamIdPaperIdRoute = ExamsExamIdPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => ExamsExamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reference': typeof ReferenceRoute
  '/exams/$examId': typeof ExamsExamIdRouteWithChildren
  '/exams/$examId/$paperId': typeof ExamsExamIdPaperIdRoute
  '/exams/$examId/': typeof ExamsExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reference': typeof ReferenceRoute
  '/exams/$examId/$paperId': typeof ExamsExamIdPaperIdRoute
  '/exams/$examId': typeof ExamsExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reference': typeof ReferenceRoute
  '/exams/$examId': typeof ExamsExamIdRouteWithChildren
  '/exams/$examId/$paperId': typeof ExamsExamIdPaperIdRoute
  '/exams/$examId/': typeof ExamsExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reference'
    | '/exams/$examId'
    | '/exams/$examId/$paperId'
    | '/exams/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reference' | '/exams/$examId/$paperId' | '/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/reference'
    | '/exams/$examId'
    | '/exams/$examId/$paperId'
    | '/exams/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReferenceRoute: typeof ReferenceRoute
  ExamsExamIdRoute: typeof ExamsExamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/': {
      id: '/exams/$examId/'
      path: '/'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof ExamsExamIdIndexRouteImport
      parentRoute: typeof ExamsExamIdRoute
    }
    '/exams/$examId/$paperId': {
      id: '/exams/$examId/$paperId'
      path: '/$paperId'
      fullPath: '/exams/$examId/$paperId'
      preLoaderRoute: typeof ExamsExamIdPaperIdRouteImport
      parentRoute: typeof ExamsExamIdRoute
    }
  }
}

interface ExamsExamIdRouteChildren {
  ExamsExamIdPaperIdRoute: typeof ExamsExamIdPaperIdRoute
  ExamsExamIdIndexRoute: typeof ExamsExamIdIndexRoute
}

const ExamsExamIdRouteChildren: ExamsExamIdRouteChildren = {
  ExamsExamIdPaperIdRoute: ExamsExamIdPaperIdRoute,
  ExamsExamIdIndexRoute: ExamsExamIdIndexRoute,
}

const ExamsExamIdRouteWithChildren = ExamsExamIdRoute._addFileChildren(
  ExamsExamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReferenceRoute: ReferenceRoute,
  ExamsExamIdRoute: ExamsExamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
